# Generated by Django 4.1.3 on 2022-11-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Item name')),
                ('description', models.TextField(verbose_name='Item Description')),
                ('price', models.PositiveIntegerField(verbose_name='Item price')),
            ],
        ),
    ]
