# Generated by Django 4.1.3 on 2022-11-17 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Currency name')),
                ('symbol', models.CharField(max_length=16, verbose_name='Currency symbol')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='stripe_id',
            field=models.CharField(default='', max_length=256, verbose_name='Sripe product ID'),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Unit price')),
                ('stripe_id', models.CharField(default='', max_length=256, verbose_name='Sripe product ID')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.currency')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.price'),
        ),
    ]
