# Generated by Django 4.1.3 on 2022-11-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_currency_item_stripe_id_price_alter_item_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.AlterField(
            model_name='item',
            name='stripe_id',
            field=models.CharField(default='', max_length=256, verbose_name='Stripe product ID'),
        ),
        migrations.AlterField(
            model_name='price',
            name='stripe_id',
            field=models.CharField(default='', max_length=256, verbose_name='Stripe product ID'),
        ),
    ]
