# Generated by Django 4.1.3 on 2022-11-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_price_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='stripe_id',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Stripe product ID'),
        ),
    ]
